apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: guardiancare
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: auth-service
