apiVersion: v1
kind: Service
metadata:
  name: check-in-service
  namespace: guardiancare
  labels:
    app: check-in-service
spec:
  type: ClusterIP
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
    name: http
  selector:
    app: check-in-service
