apiVersion: v1
kind: Service
metadata:
  name: elderly-service
  namespace: guardiancare
  labels:
    app: elderly-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: elderly-service
