apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: guardiancare
  labels:
    app: envoy
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 9901
    targetPort: 9901
    protocol: TCP
    name: admin
  selector:
    app: envoy
