apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: guardiancare
  labels:
    app: llm-service
spec:
  type: ClusterIP
  ports:
  - port: 6002
    targetPort: 6002
    protocol: TCP
    name: http
  selector:
    app: llm-service
