apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: guardiancare
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: notification-service
