apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asr-service-hpa
  namespace: guardiancare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asr-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
