apiVersion: apps/v1
kind: Deployment
metadata:
  name: elderly-service
  namespace: guardiancare
  labels:
    app: elderly-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elderly-service
  template:
    metadata:
      labels:
        app: elderly-service
    spec:
      containers:
      - name: elderly-service
        image: elderly-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: guardiancare-config
              key: ELDERLY_SERVICE_PORT
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: guardiancare-secrets
              key: JWT_SECRET
        # Readiness and liveness probes removed as health endpoint doesn't exist
        # To add them back, implement a health endpoint at /api/elderly/health
